### ISSUE TITLE
Get an error on verifying first task

### ISSUE THREAD

**Issue by nikolaykletskin** [yosuke-furukawa/tower-of-babel#52]

**Comment by yosuke-furukawa** [comment]
I think you don't have an permission to create temporary file.
please try to check your permission.

**Comment by kiwi1342** [comment]
I also have an issue with the first exercise. Bu the error I get is:


    ?exercises.BABEL SETUP.compare.title || common.exercise.compare.title || compare.title?

    /usr/local/lib/node_modules/tower-of-babel/node_modules/workshopper-exercise/comparestdout.js:19
      return new Array(sz + 1).join(ch)
         ^
    RangeError: Invalid array length
    at repeat (/usr/local/lib/node_modules/tower-of-babel/node_modules/workshopper-exercise/comparestdout.js:19:10)
    at center (/usr/local/lib/node_modules/tower-of-babel/node_modules/workshopper-exercise/comparestdout.js:25:13)
    at Exercise.transform (/usr/local/lib/node_modules/tower-of-babel/node_modules/workshopper-exercise/comparestdout.js:57:40)
    at Transform._read (/usr/local/lib/node_modules/tower-of-babel/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/usr/local/lib/node_modules/tower-of-babel/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/local/lib/node_modules/tower-of-babel/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/local/lib/node_modules/tower-of-babel/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/usr/local/lib/node_modules/tower-of-babel/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:107:17)

The verify works correctly but not the run

**Comment by ShadowManu** [comment]
@kiwi1342 just a guess here but since it doesn't look related to tower-of-babel itself, you could try to delete and reinstall it (just to be sure on sources integrity and latest accepted updates): `sudo npm uninstall -g tower-of-babel && sudo npm install -g tower-of-babel`
