### ISSUE TITLE
Babel Setup test fails

### ISSUE THREAD

**Issue by rsperberg** [yosuke-furukawa/tower-of-babel#70]
After installing babel-cli and creating a one-line program.js, I don't get the expected results when testing babel-node:

```
╭─$ sperberx in ~/dev/nodeschool/tower-of-babel [15:17:01]
╰─> cat program.js
console.log(`Hello Babel`);

╭─$ sperberx in ~/dev/nodeschool/tower-of-babel [15:17:23]
╰─> babel-node program.js
/Users/sperberx/dev/nodeschool/tower-of-babel/program.js:1
ion (exports, require, module, __filename, __dirname) { console.log(`Hello Bab
                                                                    ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at loader (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/api/register/node.js:136:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/api/register/node.js:146:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at /usr/local/lib/node_modules/babel-cli/lib/_babel-node.js:161:27
    at Object.<anonymous> (/usr/local/lib/node_modules/babel-cli/lib/_babel-node.js:162:7)
    at Module._compile (module.js:460:26)
```

As you can see, program.js contains the exact text supplied in the Babel Setup section.

And babel-node seems to be properly installed:

```
╭─$ sperberx in ~/dev/nodeschool/tower-of-babel [14:55:50]
╰─> babel-node -help

  Usage: babel-node [options] [ -e script | script.js ] [arguments]

  Options:

    -h, --help                     output usage information
    -e, --eval [script]            Evaluate script
    -p, --print [code]             Evaluate script and print result
    -o, --only [globs]             
    -i, --ignore [globs]           
    -x, --extensions [extensions]  List of extensions to hook into [.es6,.js,.es,.jsx]
    -w, --plugins [string]         
    -b, --presets [string]         
    -V, --version                  output the version number
```

So, I'm wondering what is wrong here.

Thanks for any help,

Roger Sperberg

**Comment by rsperberg** [comment]
Updating node removed the error.
