### ISSUE TITLE
Block Scope is filename dependent but description does not note that

### ISSUE THREAD

**Issue by NamespaceValentine** [yosuke-furukawa/tower-of-babel#76]
The wording of the Block Scope exercise recommends using program.js as the filename, but will fail in all cases where the filename is not "solution.js" because it reads the error message path. Either this should be noted in the description of the problem, or the diff should be done using the filename given by the verify. The latter would be preferable.

**Comment by probil** [comment]
The same issue. I get this output for different filename
```
 ACTUAL                                 EXPECTED                
==================================================
   "4"                                 ==    "4"                                
   "8"                                 ==    "8"                                
   "5"                                 ==    "5"                                
   "3"                                 ==    "3"    
   "ReferenceError: c is not defined"  ==    "ReferenceError: c is not defined" 
   "    at Object.<anonymous> (/tmp/_babel_27350/solution1.js:22:7)" !=    "    at Object.<anonymous> (/tmp/_babel_27350/solution.js:16:5)"
   "    at Module._compile (module.js:541:32)" ==    "    at Module._compile (module.js:541:32)"
   "    at Object.Module._extensions..js (module.js:550:10)" ==    "    at Object.Module._extensions..js (module.js:550:10)"
   "    at Module.load (module.js:458:32)" ==    "    at Module.load (module.js:458:32)"
   "    at tryModuleLoad (module.js:417:12)" ==    "    at tryModuleLoad (module.js:417:12)"
   "    at Function.Module._load (module.js:409:3)" ==    "    at Function.Module._load (module.js:409:3)"
   "    at Function.Module.runMain (module.js:575:10)" ==    "    at Function.Module.runMain (module.js:575:10)"
   "    at startup (node.js:160:18)"   ==    "    at startup (node.js:160:18)"  
   "    at node.js:456:3"              ==    "    at node.js:456:3"             
   ""                                  ==    ""      
```

**Comment by prochafilho** [comment]
Thank you for clarifying that. I am surprised that more people don't notice that.

**Comment by rubramriv73** [comment]
Easy solution to this issue: 
catch(e){
  console.log(e.message)
}

in both solution.js and program.js 

Hope it get resolved by that
