### ISSUE TITLE
Verification of correct exercise 6 Block Scope fails

### ISSUE THREAD

**Issue by RegalMedia** [yosuke-furukawa/tower-of-babel#90]
When verifying a correct solution to exercise 6, the verification fails if the source program file is not named "solution.js", since the stack trace messages being compared contain file names and line/column numbers that won't exactly match otherwise.

Ran this:
`tower-of-babel verify program6.js`

Issue occurs even when program6.js contains the same exact source as the committed solution.  File name and/or line:col of the exception won't match.

First tests pass...
```
                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "4"                                 ==    "4"                                
   "8"                                 ==    "8"                                
   "5"                                 ==    "5"                                
   "14"                                ==    "14"                               
   "ReferenceError: c is not defined"  ==    "ReferenceError: c is not defined" 
```
This test fails...
```
   "    at Object.<anonymous> (/private/var/folders/5m/m78m29z90fbbv84zvb1_bgl00000gn/T/_babel_10109/program6.js:24:7)" !=    "    at Object.<anonymous> (/private/var/folders/5m/m78m29z90fbbv84zvb1_bgl00000gn/T/_babel_10109/solution.js:16:5)"
```
Remaining tests pass...
```
   "    at Module._compile (module.js:635:30)" ==    "    at Module._compile (module.js:635:30)"
   "    at Object.Module._extensions..js (module.js:646:10)" ==    "    at Object.Module._extensions..js (module.js:646:10)"
   "    at Module.load (module.js:554:32)" ==    "    at Module.load (module.js:554:32)"
   "    at tryModuleLoad (module.js:497:12)" ==    "    at tryModuleLoad (module.js:497:12)"
   "    at Function.Module._load (module.js:489:3)" ==    "    at Function.Module._load (module.js:489:3)"
   "    at Function.Module.runMain (module.js:676:10)" ==    "    at Function.Module.runMain (module.js:676:10)"
   "    at startup (bootstrap_node.js:187:16)" ==    "    at startup (bootstrap_node.js:187:16)"
   "    at bootstrap_node.js:608:3"    ==    "    at bootstrap_node.js:608:3"   
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

✗ Submission results did not match expected!

# FAIL

Your solution to BLOCK SCOPE didn't pass. Try again!
```

**Comment by davidlares** [comment]
I was facing the same problem and I solved it by changing the Js File name to 'solution.js', it seems very unpractical but is the only way to pass the challenge. It should be fixed.
